### ISSUE TITLE
vulkan has stopped working after an update

### ISSUE THREAD

**Issue by D0nnieD4rk0** [Frogging-Family/mesa-git#17]
im on pretty old hardware so it might be the cause, but it ran fine before an update so there has to be a way to fix it

Hardware:
```[System]
OS:              EndeavourOS rolling rolling
Arch:            x86_64
Kernel:          5.19.10-269-tkg-cfs
Desktop:         GNOME
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i3-3227U CPU @ 1.90GHz
Physical cores:  2
Logical cores:   4

[Memory]
RAM:             3.7 GB
Swap:            8.0 GB

[Graphics]
Vendor:          Intel
OpenGL Renderer: Mesa Intel(R) HD Graphics 4000 (IVB GT2)
OpenGL Version:  4.2 (Compatibility Profile) Mesa 22.3.0-devel (git-35c40c64c8)
OpenGL Core:     4.2 (Core Profile) Mesa 22.3.0-devel (git-35c40c64c8)
OpenGL ES:       OpenGL ES 3.0 Mesa 22.3.0-devel (git-35c40c64c8)
Vulkan:          Not Supported
```

vulkaninfo:
`ERROR: [Loader Message] Code 0 : setup_loader_term_phys_devs:  Failed to detect any valid GPUs in the current config
ERROR at /build/vulkan-tools/src/Vulkan-Tools-1.3.226/vulkaninfo/vulkaninfo.h:237:vkEnumeratePhysicalDevices failed with ERROR_INITIALIZATION_FAILED`

any suggestions ?

thanks

**Comment by Etaash-mathamsetty** [comment]
also having this issue, this should be fixed urgently 
![image](https://user-images.githubusercontent.com/45927311/193308004-4dac7123-6f37-4291-888b-df85b37abe9e.png)

**Comment by Tk-Glitch** [comment]
Please keep in mind mesa-git is prone to break :frog:

**Comment by D0nnieD4rk0** [comment]
even regular mesa has this issue 💀

**Comment by Tk-Glitch** [comment]
This specific issue was on legacy intel GPUs. The RADV breakage is a different issue, which is totally upstream.
