### ISSUE TITLE
Vulkan has stopped working after an update (AMD)

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [Frogging-Family/mesa-git#18]
![image](https://user-images.githubusercontent.com/45927311/193308444-de850198-bfb3-4f15-86ae-634a142ed99a.png)
should be fixed urgently....
could also be an upstream issue, but im not so sure, so I want to submit this here first

**Comment by EmptyVisual** [comment]
Upstream issue, Fixed in https://gitlab.freedesktop.org/mesa/mesa/-/commit/0e6d44d14fa1fd4ff15974d1aee146498fd88c03

**Comment by Etaash-mathamsetty** [comment]
> Upstream issue, Fixed in https://gitlab.freedesktop.org/mesa/mesa/-/commit/0e6d44d14fa1fd4ff15974d1aee146498fd88c03

yes I am aware of that, am waiting for chaotic aur now.
