### ISSUE TITLE
Failure to compile src/gallium/drivers/softpipe/48c2f4b@@softpipe@sta/sp_tex_sample.c.o

### ISSUE THREAD

**Issue by HurricanePootis** [Frogging-Family/mesa-git#2]
My terminal spits out the following when it fails to compile.
`[1890/2578] Compiling C object 'src/gallium/drivers/softpipe/48c2f4b@@softpipe@sta/sp_tex_sample.c.o'
FAILED: src/gallium/drivers/softpipe/48c2f4b@@softpipe@sta/sp_tex_sample.c.o 
gcc -Isrc/gallium/drivers/softpipe/48c2f4b@@softpipe@sta -Isrc/gallium/drivers/softpipe -I../mesa/src/gallium/drivers/softpipe -Isrc/gallium/auxiliary -I../mesa/src/gallium/auxiliary -I../mesa/src/gallium/include -Iinclude -I../mesa/include -Isrc -I../mesa/src -fvisibility=hidden -fdiagnostics-color=always -DNDEBUG -pipe -D_FILE_OFFSET_BITS=64 -std=c99 -Wl,--gc-sections -ffunction-sections -fdata-sections -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS '-DPACKAGE_VERSION="20.2.0-devel"' '-DPACKAGE_BUGREPORT="https://gitlab.freedesktop.org/mesa/mesa/-/issues"' -DUSE_ELF_TLS -DHAVE_ST_VDPAU -DENABLE_ST_OMX_BELLAGIO=1 -DENABLE_ST_OMX_TIZONIA=0 -DHAVE_X11_PLATFORM -DGLX_INDIRECT_RENDERING -DGLX_DIRECT_RENDERING -DGLX_USE_DRM -DHAVE_DRM_PLATFORM -DENABLE_SHADER_CACHE -DHAVE___BUILTIN_BSWAP32 -DHAVE___BUILTIN_BSWAP64 -DHAVE___BUILTIN_CLZ -DHAVE___BUILTIN_CLZLL -DHAVE___BUILTIN_CTZ -DHAVE___BUILTIN_EXPECT -DHAVE___BUILTIN_FFS -DHAVE___BUILTIN_FFSLL -DHAVE___BUILTIN_POPCOUNT -DHAVE___BUILTIN_POPCOUNTLL -DHAVE___BUILTIN_UNREACHABLE -DHAVE_FUNC_ATTRIBUTE_CONST -DHAVE_FUNC_ATTRIBUTE_FLATTEN -DHAVE_FUNC_ATTRIBUTE_MALLOC -DHAVE_FUNC_ATTRIBUTE_PURE -DHAVE_FUNC_ATTRIBUTE_UNUSED -DHAVE_FUNC_ATTRIBUTE_WARN_UNUSED_RESULT -DHAVE_FUNC_ATTRIBUTE_WEAK -DHAVE_FUNC_ATTRIBUTE_FORMAT -DHAVE_FUNC_ATTRIBUTE_PACKED -DHAVE_FUNC_ATTRIBUTE_RETURNS_NONNULL -DHAVE_FUNC_ATTRIBUTE_ALIAS -DHAVE_FUNC_ATTRIBUTE_NORETURN -DHAVE_FUNC_ATTRIBUTE_VISIBILITY -DHAVE_UINT128 -D_GNU_SOURCE -DUSE_SSE41 -DUSE_GCC_ATOMIC_BUILTINS -DUSE_X86_64_ASM -DMAJOR_IN_SYSMACROS -DHAVE_LINUX_FUTEX_H -DHAVE_ENDIAN_H -DHAVE_DLFCN_H -DHAVE_EXECINFO_H -DHAVE_SYS_SHM_H -DHAVE_CET_H -DHAVE_STRTOF -DHAVE_MKOSTEMP -DHAVE_TIMESPEC_GET -DHAVE_MEMFD_CREATE -DHAVE_RANDOM_R -DHAVE_FLOCK -DHAVE_STRTOK_R -DHAVE_GETRANDOM -DHAVE_PROGRAM_INVOCATION_NAME -DHAVE_POSIX_MEMALIGN -DHAVE_DIRENT_D_TYPE -DHAVE_STRTOD_L -DHAVE_DLADDR -DHAVE_DL_ITERATE_PHDR -DHAVE_ZLIB -DHAVE_ZSTD -DHAVE_PTHREAD -DHAVE_PTHREAD_SETAFFINITY -DHAVE_LIBDRM -DLLVM_AVAILABLE '-DMESA_LLVM_VERSION_STRING="10.0.0"' -DUSE_LIBGLVND=1 -DHAVE_VALGRIND -DHAVE_LIBUNWIND -DHAVE_WAYLAND_PLATFORM -DWL_HIDE_DEPRECATED -DHAVE_DRI3 -DHAVE_DRI3_MODIFIERS -DHAVE_GALLIUM_EXTRA_HUD=1 -DHAVE_LIBSENSORS=1 -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=return-type -Werror=empty-body -Werror=incompatible-pointer-types -Werror=int-conversion -Wimplicit-fallthrough -Wno-missing-field-initializers -Wno-format-truncation -fno-math-errno -fno-trapping-math -fno-common -Werror=format -Wformat-security -march=x86-64 -mtune=generic -O2 -fstack-protector-strong -fno-plt -D_FORTIFY_SOURCE=2 -fPIC -Werror=pointer-arith -Werror=vla -MD -MQ 'src/gallium/drivers/softpipe/48c2f4b@@softpipe@sta/sp_tex_sample.c.o' -MF 'src/gallium/drivers/softpipe/48c2f4b@@softpipe@sta/sp_tex_sample.c.o.d' -o 'src/gallium/drivers/softpipe/48c2f4b@@softpipe@sta/sp_tex_sample.c.o' -c ../mesa/src/gallium/drivers/softpipe/sp_tex_sample.c
during IPA pass: fnsummary
../mesa/src/gallium/drivers/softpipe/sp_tex_sample.c: In function ‘sample_compare’:
../mesa/src/gallium/drivers/softpipe/sp_tex_sample.c:3862:1: internal compiler error: Segmentation fault
 3862 | }
      | ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://bugs.archlinux.org/> for instructions.
[1903/2578] Compiling C++ object 'src/gallium/drivers/swr/3eb908b@@mesaswr@sta/meson-generated_.._rasterizer_core_backends_gen_rasterizer3.cpp.o'
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...
  -> Cleanup done
`

**Comment by Tk-Glitch** [comment]
https://gitlab.freedesktop.org/mesa/mesa/-/issues/3242

**Comment by HurricanePootis** [comment]
Thanks for the reply, but I have fixed the issue by reinstalling all of the make dependencies.
