### ISSUE TITLE
Mesa mirror on Github has out-of-date tags;Mesa gitlab speed is fast now

### ISSUE THREAD

**Issue by HurricanePootis** [Frogging-Family/mesa-git#25]
Hello,

So, I know y'all switched to `https://github.com/mesa3d/mesa` for the PKGBUILD because it was faster than the official gitlab. But, if you take a look at `https://github.com/mesa3d/mesa/tags` and `https://gitlab.freedesktop.org/mesa/mesa/-/tags`, you can see that the `gitlab.freedesktop.org`'s tags are up to the current version.

Therefore, knowing this and that I was able to git clone the `gitlab.freedesktop.org` with the same speed as the `github.com` mirror, I think maybe that the PKGBUILD should default to `gitlab.freedesktop.org`

Thank you for reading!

**Comment by xDShot** [comment]
Yes, it came to realization that the package fails to pull latest commits from freedesktop repo and I see it now why.

**Comment by intrnl** [comment]
Chaotic-AUR has its own Mesa mirror on GitHub for an alternative, trust at your own risk however
https://github.com/chaotic-aur/mesa-mirror

personally the freedesktop GitLab instance is just too slow for me, I can't even load its web UI either.
