### ISSUE TITLE
Meson build error: Unknown options: "dri-drivers"

### ISSUE THREAD

**Issue by tjumar** [Frogging-Family/mesa-git#27]
Hello,
the meson option "dri-drivers" was removed in https://gitlab.freedesktop.org/mesa/mesa/-/commit/59625a68ffc592cc5c6c62baf3a03853f234dbf2
the build fails now with: mesa/meson.build:21:0: ERROR: Unknown options: "dri-drivers"

**Comment by Duneathor** [comment]
#28 
See PR

**Comment by Tk-Glitch** [comment]
Fixed following https://github.com/Frogging-Family/mesa-git/commit/911f4b457755133c7c10e8e57132aed08f6a53f8
