### ISSUE TITLE
ERROR: Dependency "clang" not found, tried cmake

### ISSUE THREAD

**Issue by nutta-git** [Frogging-Family/mesa-git#5]
both clang and cmake are installed on the system 
[meson-log.txt](https://github.com/Frogging-Family/mesa-git/files/5585711/meson-log.txt)

OS: Arch Linux
Found this on gitlab, 
https://gitlab.freedesktop.org/mesa/mesa/-/issues/3873

current solution: 
revert commit `a5227465c13ae74651a932a82aeae65683f4a063` when compiling mesa

**Comment by ronoverdrive** [comment]
Getting the same thing here.

**Comment by ObserverOfTime** [comment]
So it's a meson issue. Who'd have thought…

**Comment by nutta-git** [comment]
@ObserverOfTime 
I tired doing what you have said and have meet with some issues. 
`ln: failed to create symbolic link '/home/corn/src/mesa-git/a5227465c13ae74651a932a82aeae65683f4a063.mymesarevert': File exists
`
Steps I took: 
`cd` into the `mesa-userpatches` directory. 
next, `wget`  https://gitlab.freedesktop.org/mesa/mesa/-/commit/a5227465c13ae74651a932a82aeae65683f4a063.diff 
then, `mv` a5227465c13ae74651a932a82aeae65683f4a063.diff a5227465c13ae74651a932a82aeae65683f4a063.mymesarevert
 after which I inserted a5227465c13ae74651a932a82aeae65683f4a063.mymesarevert to `_community_patches` in `customization.cfg `

Are these the steps you too? if not, would you mind sharing the instruction on how to?

**Comment by benoit-pierre** [comment]
Easier to patch `meson.build` in the `PKGBUILD`'s `prepare`:
```diff
 PKGBUILD | 2 ++
 1 file changed, 2 insertions(+)

diff --git i/PKGBUILD w/PKGBUILD
index 28206f1..863b221 100644
--- i/PKGBUILD
+++ w/PKGBUILD
@@ -269,6 +269,8 @@ prepare() {
       rm -f "$_where"/$_pr.mymesapatch
     done
 
+    sed -i "s/required : get_option('microsoft-clc'),/required : false,/p" meson.build
+
     cd "$srcdir"
 
     # although removing _build folder in build() function feels more natural,
```

**Comment by nutta-git** [comment]
@benoit-pierre 
Thank you! That worked!

**Comment by ObserverOfTime** [comment]
You shouldn't add it to `_community_patches` because it's not a community patch.
