### ISSUE TITLE
util/macros.h: No such file or directory

### ISSUE THREAD

**Issue by HurricanePootis** [Frogging-Family/mesa-git#6]
Using the latest PKGBUILD, I get the following error:

> `[433/2605] Compiling C object src/vulkan/device-select-layer/libVkLayer_MESA_device_select.so.p/device_select_layer.c.o
> FAILED: src/vulkan/device-select-layer/libVkLayer_MESA_device_select.so.p/device_select_layer.c.o 
> gcc -Isrc/vulkan/device-select-layer/libVkLayer_MESA_device_select.so.p -Isrc/vulkan/device-select-layer -I../mesa/src/vulkan/device-select-layer -Iinclude -I../mesa/include -Isrc/util -I../mesa/src/util -Isrc/vulkan/wsi -I../mesa/src/vulkan/wsi -Isrc/vulkan/util -I../mesa/src/vulkan/util -Isrc/egl/wayland/wayland-drm -I/usr/include/valgrind -I/usr/include/libdrm -fvisibility=hidden -fdiagnostics-color=always -DNDEBUG -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c99 -O3 -ffunction-sections -fdata-sections -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS '-DPACKAGE_VERSION="21.0.0-devel"' '-DPACKAGE_BUGREPORT="https://gitlab.freedesktop.org/mesa/mesa/-/issues"' -DUSE_ELF_TLS -DHAVE_ST_VDPAU -DENABLE_ST_OMX_BELLAGIO=1 -DENABLE_ST_OMX_TIZONIA=0 -DHAVE_X11_PLATFORM -DHAVE_XCB_PLATFORM -DGLX_INDIRECT_RENDERING -DGLX_DIRECT_RENDERING -DGLX_USE_DRM -DHAVE_DRM_PLATFORM -DENABLE_SHADER_CACHE -DHAVE___BUILTIN_BSWAP32 -DHAVE___BUILTIN_BSWAP64 -DHAVE___BUILTIN_CLZ -DHAVE___BUILTIN_CLZLL -DHAVE___BUILTIN_CTZ -DHAVE___BUILTIN_EXPECT -DHAVE___BUILTIN_FFS -DHAVE___BUILTIN_FFSLL -DHAVE___BUILTIN_POPCOUNT -DHAVE___BUILTIN_POPCOUNTLL -DHAVE___BUILTIN_UNREACHABLE -DHAVE_FUNC_ATTRIBUTE_CONST -DHAVE_FUNC_ATTRIBUTE_FLATTEN -DHAVE_FUNC_ATTRIBUTE_MALLOC -DHAVE_FUNC_ATTRIBUTE_PURE -DHAVE_FUNC_ATTRIBUTE_UNUSED -DHAVE_FUNC_ATTRIBUTE_WARN_UNUSED_RESULT -DHAVE_FUNC_ATTRIBUTE_WEAK -DHAVE_FUNC_ATTRIBUTE_FORMAT -DHAVE_FUNC_ATTRIBUTE_PACKED -DHAVE_FUNC_ATTRIBUTE_RETURNS_NONNULL -DHAVE_FUNC_ATTRIBUTE_ALIAS -DHAVE_FUNC_ATTRIBUTE_NORETURN -DHAVE_FUNC_ATTRIBUTE_VISIBILITY -DHAVE_UINT128 -D_GNU_SOURCE -DUSE_SSE41 -DUSE_GCC_ATOMIC_BUILTINS -DUSE_X86_64_ASM -DMAJOR_IN_SYSMACROS -DHAVE_LINUX_FUTEX_H -DHAVE_ENDIAN_H -DHAVE_DLFCN_H -DHAVE_EXECINFO_H -DHAVE_SYS_SHM_H -DHAVE_CET_H -DHAVE_STRTOF -DHAVE_MKOSTEMP -DHAVE_TIMESPEC_GET -DHAVE_MEMFD_CREATE -DHAVE_RANDOM_R -DHAVE_FLOCK -DHAVE_STRTOK_R -DHAVE_GETRANDOM -DHAVE_PROGRAM_INVOCATION_NAME -DHAVE_POSIX_MEMALIGN -DHAVE_DIRENT_D_TYPE -DHAVE_STRTOD_L -DHAVE_DLADDR -DHAVE_DL_ITERATE_PHDR -DHAVE_ZLIB -DHAVE_ZSTD -DHAVE_PTHREAD -DHAVE_PTHREAD_SETAFFINITY -DHAVE_LIBDRM -DLLVM_AVAILABLE '-DMESA_LLVM_VERSION_STRING="11.0.0"' -DLLVM_IS_SHARED=1 -DUSE_LIBGLVND=1 -DHAVE_VALGRIND -DHAVE_LIBUNWIND -DHAVE_WAYLAND_PLATFORM -DWL_HIDE_DEPRECATED -DHAVE_DRI3 -DHAVE_DRI3_MODIFIERS -DHAVE_GALLIUM_EXTRA_HUD=1 -DHAVE_LIBSENSORS=1 -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=return-type -Werror=empty-body -Werror=incompatible-pointer-types -Werror=int-conversion -Wimplicit-fallthrough -Wno-missing-field-initializers -Wno-format-truncation -fno-math-errno -fno-trapping-math -fno-common -Werror=format -Wformat-security -march=x86-64 -mtune=generic -O2 -fno-plt -D_FORTIFY_SOURCE=2 -fPIC -pthread -Wno-override-init -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_WAYLAND_KHR -MD -MQ src/vulkan/device-select-layer/libVkLayer_MESA_device_select.so.p/device_select_layer.c.o -MF src/vulkan/device-select-layer/libVkLayer_MESA_device_select.so.p/device_select_layer.c.o.d -o src/vulkan/device-select-layer/libVkLayer_MESA_device_select.so.p/device_select_layer.c.o -c ../mesa/src/vulkan/device-select-layer/device_select_layer.c
> In file included from ../mesa/src/vulkan/device-select-layer/device_select_layer.c:43:
> ../mesa/src/vulkan/util/vk_util.h:26:10: fatal error: util/macros.h: No such file or directory
>    26 | #include "util/macros.h"
>       |          ^~~~~~~~~~~~~~~
> compilation terminated.
> [446/2605] Compiling C++ object src/imgui/libimgui_core.a.p/imgui_widgets.cpp.o
> ninja: build stopped: subcommand failed.
> ==> ERROR: A failure occurred in build().
>     Aborting...
>   -> Cleanup done
> `

I am on the latest version of Arch, kernel 5.9.11-96-tkg-cfs

**Comment by Tk-Glitch** [comment]
Fixed upstream https://gitlab.freedesktop.org/mesa/mesa/-/issues/3901
